### ISSUE TITLE
Schema CamelCase not handling @default("{}") correctly

### ISSUE THREAD

**Issue by ajhollowayvrm** [paljs/prisma-tools#256]
schema.prisma before
```
model access_overrides {
  id        BigInt @id @default(autoincrement())
  overrides Json?  @default("{}")

  @@index([id], map: "access_overrides_index")
}
```

schema.prisma after `pal schema camel-case`
```
model AccessOverrides {
  id        BigInt @id @default(autoincrement())
  overrides Json?  @default("{}")

  @@index([id], map: "access_overrides_index")
  @@map("access_overrides")
}
")
@@index([id], map: "access_overrides_index")
}
```

Notice it seems to copy everything after the closing `}` character and repeat it minus the map. 

I'm on the latest versions of PalJS and Prisma. Any help would be appreciated.

**Comment by AhmedElywa** [comment]
I already fixed this in the last version 4.0.14

**Comment by ajhollowayvrm** [comment]
Hmm I'm using this command `npx @paljs/cli schema camel-case` and this command `pal schema camel-case` on this version 
```
VERSION
  @paljs/cli/4.0.15 darwin-x64 node-v14.17.4
```

and I'm still getting this error.
