### ISSUE TITLE
Support Prisma 5.0.0 version

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [paljs/prisma-tools#298]
I have updated my npm packages to the new version when I did this I got an error while installing the packages
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project-api@0.0.1
npm ERR! Found: @prisma/client@5.0.0
npm ERR! node_modules/@prisma/client
npm ERR!   @prisma/client@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @prisma/client@"^4" from @paljs/plugins@5.3.3
npm ERR! node_modules/@paljs/plugins
npm ERR!   @paljs/plugins@"^5.3.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by AhmedElywa** [comment]
There are a lot of breaking changes that need to handle first before releasing the new version supporting Prisma. V5

**Comment by AhmedElywa** [comment]
we pushed V6 that support prisma v5

**Comment by f8k8** [comment]
Trying to install the latest version gives an error:

```
npm ERR! Found: @prisma/client@5.2.0
npm ERR! node_modules/@prisma/client
npm ERR!   @prisma/client@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @prisma/client@"^4" from @paljs/plugins@6.0.1
npm ERR! node_modules/@paljs/plugins
npm ERR!   @paljs/plugins@"^6.0.0" from the root project
```
It looks like the packages still have a dependency on Prisma 4

**Comment by AhmedElywa** [comment]
Oh yes, I forgot to change the peer dependency will fix it.

**Comment by AhmedElywa** [comment]
Fixed in v6.0.2

**Comment by woss** [comment]
custom prisma client path is not working. DMMF signature is not the same
